### PR TITLE
fix prefix config

### PR DESCRIPTION
**Pull request by dennyjuice**
When I added a prefix to the config, it became undefined_. If change service to config everything works as expected

### CODE REVIEW

**Comment by XanderD99** [comment]
fixed this issue and created new version 1.7.0

**Comment by dennyjuice** [comment]
Cool, But I closed this request, because now if you do not pass the prefix in the config, it will be undefined, and the prefix is added only to the metrics of the process, and not to the rest :)

**Comment by XanderD99** [comment]
Oh well, that's not ideal. I'll check it and fix it asap, but won't be until tomorrow the earliest as I have an long flight home

**Comment by dennyjuice** [comment]
Nothing terrible, thank you :)

**Comment by XanderD99** [comment]
The issue should be fixed completely in version 1.8.0, prefix is now added to all metrics and should also be added to all metrics if you add them using the metrics service of the plugin. 
an "_" is also added automatically to match the casing :)

**Pull request closed without merging**
